### ISSUE TITLE
Does it support react?

### ISSUE THREAD

**Issue by yuanguandong** [neuronetio/gantt-elastic#94]
Does it support react?

**Comment by neuronetio** [comment]
It could, but you need to wrap gantt-elastic into react component.
Right now there is no official react component.
You can fund it if you want.

**Comment by eyelly-wu** [comment]
**1.How  to wrap gantt-elastic into react component，is API provided？**

**2.This example only shows how to use it in Vue(Two ways), but how to use it in other frameworks?**
![image](https://user-images.githubusercontent.com/24505069/71793757-36653580-3079-11ea-9078-83c9382e3f29.png)

**Comment by neuronetio** [comment]
If you know your framework you should be able to make it work.
I don't have time for this version because I'm working on second version right now [gantt-schedule-timeline-calendar](https://github.com/neuronetio/gantt-schedule-timeline-calendar)
google it - `how to wrap ... component in react` or something similar
